### ISSUE TITLE
Define used cc65 version

### ISSUE THREAD

**Issue by bclausdorff** [cirla/nesdev#2]
Syntax for configuration files or commands might change from version to version.
see #1 

To prevent frustration, the used cc65 version should be named in the README file.

Also it should be mentioned in the tutorial. (Which is great by the way 👍 )

**Comment by cirla** [comment]
Great catch, thanks!

I've been using the [`master`](https://github.com/cc65/cc65) branch (V2.15) of the actively developed [`cc65` on github](https://github.com/cc65/cc65). I should be explicit about that in the first two posts (Hello, World! parts 1 and 2).

**Comment by cirla** [comment]
Please see https://github.com/cirla/nesdev/commit/9241cb6f93f85736798fe4acca8b9a3c2c000b03 and https://github.com/cirla/nesdev/commit/cd6c61ab118b324291ada99fec95d4ae589255df and let me know if this is satisfactory. Thanks!

**Comment by bclausdorff** [comment]
Maybe it would be good to add the note to the README of the other branches as well.
Especially the master branch. For most visitors of the repo, it will be the first branch they see.

**Comment by cirla** [comment]
Good call. See https://github.com/cirla/nesdev/commit/cbe7ad44d26740a005ded96888365eb3908e3a32, https://github.com/cirla/nesdev/commit/2d25a59d1e3763df10821d0aec8ecd65b87af859, and https://github.com/cirla/nesdev/commit/57225e22c64f851b554664f31fd97b24f4b0a0bb and feel free to close if you're satisfied.

**Comment by bclausdorff** [comment]
Really nice, thank you!
