### ISSUE TITLE
The parameter stack is not configured correctly.

### ISSUE THREAD

**Issue by holmak** [cirla/nesdev#3]
The parameter stack in this project is not set up correctly: it is placed on page one, starting at the exact same address as the hardware return stack. If you attempt to use functions that take arguments, or local variables in functions, they will overwrite return addresses on the 6502's hardware return stack.

Your current code doesn't have any problems, because its C code never uses function arguments or local variables. However, if a hapless tutorial reader (like me), tries to write typical C code with function arguments or locals, the program will soon start behaving erratically and eventually crash.

The cc65 compiler uses a separate stack for function arguments and local variables: the "parameter stack". It is typically placed at the end of RAM, and occupies a configurable number of pages. The usage of the return and parameter stacks in cc65 is documented here: https://github.com/cc65/wiki/wiki/Parameter-and-return-stacks

You can see how cc65's default linker configuration files reserve space at the end of RAM for the parameter stack: https://github.com/cc65/cc65/blob/master/cfg/nes.cfg

I believe the correct fix would be to initialize the parameter stack (`sp`) to start at the end of NES RAM (`$07FF`), and, optionally, to reduce the "RAM" memory region (in the `.cfg` file) to reserve some space for the parameter stack.

By the way, thanks for writing this tutorial and providing this sample code. It was very helpful for me getting my NES project started!

(Edited: Fixed the address of end of RAM.)

**Comment by cirla** [comment]
First of all, sorry for the abysmal turnaround time on this issue and thanks so much for the feedback!

It seems I had conflated the 6502 CPU stack and the C stack exactly as you describe above. That would explain why my code stopped working when I used function arguments that didn't fit into registers via `__fastcall__`!

Thanks again for catching this. I've updated the cfg files in all of the code branches and the relevant blog post.
